export const ACCOUNT_EMAIL_VERIFICATION_SERVICE_PROVIDER_NAME =
  'ACCOUNT_EMAIL_VERIFICATION_SERVICE';
export const REQUEST_EMAIL_VERIFICATION_SERVICE_PROVIDER_NAME =
  'REQUEST_EMAIL_VERIFICATION_SERVICE';
export const USER_NOT_VERIFIED_JWT_STRATEGY_NAME = 'USERS_NOT_FOUND_ACCESS_JWT_STRATEGY';
