export const MONGO_QUERY_PARSER_PROVIDER_NAME = 'MONGO_QUERY_PARSER';
export const PAGINATOR_PROVIDER_NAME = 'PAGINATOR';
export const MAIL_SERVICE_PROVIDER_NAME = 'MAIL_SERVICE';
export const HASHING_SERVICE_PROVIDER_NAME = 'HASHING_SERVICE';
