// Roles
export const ROLES_SERVICE_PROVIDER_NAME = 'ROLES_SERVICE';
// Permissions
export const PERMISSIONS_SERVICE_PROVIDER_NAME = 'PERMISSIONS_SERVICE';
// Auth
export const AUTH_SERVICE_PROVIDER_NAME = 'AUTH_SERVICE';
